version: "3.8"
services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: doctor_appointment_system
    ports:
      - "8080:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
